import type { Metadata } from "next";
import "./globals.css";

import SiteProviders from "./providers/SiteProviders";
import Navbar from "./_components/Navbar";
import { Permanent_Marker } from "next/font/google";

const permanentMarker = Permanent_Marker({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${permanentMarker.className} min-h-screen bg-base-300`}>
        <SiteProviders>
          <Navbar />
          {children}
        </SiteProviders>
      </body>
    </html>
  );
}
